name: Bug report
description: Report a reproducible bug or regression
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail for us to reproduce it.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the issue
      placeholder: What went wrong?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps and inputs used
      placeholder: |
        1. Start server with...
        2. Call tool...
        3. Observe...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened?
    validations:
      required: true
  - type: input
    id: node_version
    attributes:
      label: Node.js version
      placeholder: e.g. v20.19.0
    validations:
      required: true
  - type: input
    id: package_version
    attributes:
      label: Package version
      placeholder: e.g. 1.0.4
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or stack traces
      render: shell
